---
# ansible/roles/db_storage/tasks/main.yml

#- name: Ensure the /data directory (for DB storage) exists
#  file: path=/data state=directory

- name: Format the block storage device at /dev/xvdp with an ext4 file system
  filesystem: fstype=ext4 dev=/dev/xvdp
  become: true

# Note that this also modifies /etc/fstab so the mount will persist through a crash.
# To better understand the /etc/fstab fields/columns, see:
# http://man7.org/linux/man-pages/man5/fstab.5.html
# https://tinyurl.com/jmmsyon = the soure code of the mount module
- name: Ensure /data dir exists and is mounted + update /etc/fstab
  mount:
    name=/data
    src=/dev/xvdp
    fstype=ext4
    opts="defaults,nofail,nobootwait"
    dump=0
    passno=2
    state=mounted
  become: true

# Modify the I/O scheduler? Is that even a good idea?
# Must do this in /sys/block/xvdp/queue/scheduler
# and also with grub (so the I/O scheduler stays changed on reboot)
# Example: https://gist.github.com/keithchambers/80b60559ad83cebf1672
