---
# ansible/roles/bigchaindb/tasks/main.yml

# Note: "become: true" basically means "become root user for this task" i.e. sudo <cmd>
# See https://docs.ansible.com/ansible/become.html

# Note: update_cache=yes means it will do the equivalent of
# sudo apt-get update before the operation.
- name: Ensure the latest BigchainDB-required Ubuntu packages are installed
  apt: name={{item}} state=latest update_cache=yes
  become: true
  with_items:
    - git
    - g++
    - python3-dev
    - python3-setuptools  # mainly for easy_install3, which is used to get latest pip3

# This should make both pip and pip3 be pip version >=8.1.2 (python 3.4).
# See the comments about this below.
- name: Ensure the latest pip/pip3 is installed, using easy_install3
  easy_install: executable=easy_install3 name=pip state=latest
  become: true

- name: Ensure the latest setuptools (Python package) is installed
  pip: executable=pip3 name=setuptools state=latest
  become: true

- name: Install BigchainDB from PyPI using sudo pip3 install bigchaindb
  pip: executable=pip3 name=bigchaindb state=latest
  become: true

- name: Gather facts about the file ~/.bigchaindb
  stat: path={{ ansible_env.HOME }}/.bigchaindb
  register: home_bigchaindb_config_file

- name: If ~/.bigchaindb doesn't exist, generate a default BigchainDB config file there
  shell: bigchaindb -y configure
  when: not home_bigchaindb_config_file.stat.exists

- name: Look up all processes with 'bigchaindb' in their name
  shell: pgrep bigchaindb
  ignore_errors: true
  changed_when: false
  register: pgrep_bigchaindb

# pgrep_bigchaindb.rc (return code) should be 0 if a bigchaindb process is already running

- name: Ensure a copy of start_bigchaindb.sh is on the remote host
  copy: src=start_bigchaindb.sh dest=/tmp/start_bigchaindb.sh mode=0775
  become: true

# Running BigchainDB in the background from Ansible is tricky, see:
# https://superuser.com/questions/870871/run-a-remote-script-application-in-detached-mode-in-ansible
- name: If BigchainDB isn't running then run it
  command: /tmp/start_bigchaindb.sh
  async: 45
  poll: 0
  when: pgrep_bigchaindb.rc != 0


# Notes about getting the latest version of pip3:
#
# The first way I tried to get the latest pip3 (commented-out below) didn't work.
# The first task works, but then the attempt to do
# the equivalent of "pip install -U pip" fails. "Found existing installation"
# and it didn't want to uninstall it

# Installing the python3-pip package installs a Python 3 version of pip named pip3
#- name: Ensure the latest python-pip and python3-pip Ubuntu packages are installed
#  apt: name={{item}} state=latest update_cache=yes
#  become: true
#  with_items:
#    - python-pip
#    - python3-pip
#
#- name: Ensure pip is the latest version
#  pip: executable=pip name=pip state=latest
#
#- name: Ensure pip3 is the latest version
#  pip: executable=pip3 name=pip state=latest